### PR TITLE
feat: Upgrade to Angular 13

### LINKED ISSUE #357: Upgrade to Angular 13
To leverage all new features in Angular 13 (see https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296), we should upgrade this repository and change the build configuration to `Ivy Partial`. 

I have proposed PR #356 to this end. This will make sure consumers of this package no longer face the `ngcc` steps, improving everybody's development experience!

### PR DESCRIPTION
**Pull request by Timebutt**
This PR upgrades `ngx-color` to Angular 13. I had to make a few changes to please `ng-packagr`, as in version 13 both the API changed (see `build.ts` changes), and `ng-packagr` became stricter (hence the need for individual `public_api.ts` files per package).

fixes #357

### CODE REVIEW

**Comment by scttcper** [comment]
I assume this is a breaking change that requires v13?

**Comment by Timebutt** [comment]
It is breaking in that it requires the consuming app to run `Ivy`. The `"compilationMode": "partial"` setting makes sure this works with Angular applications of all versions, as long as they are running `Ivy`. AFAIK, very few applications are Angular 9+ and are still running `View Engine` (there were some numbers on a blog post somewhere, I'll see if I can dig those up).

**Comment by Timebutt** [comment]
Thanks for getting this merged and shipped this fast 🚀

**Comment by Timebutt** [comment]
Ok bad news, just tried running a build with version `7.3.0` of this package installed and it failed. Apparently the new `APF` (Angular Package Format) enables the use of `exports` field in the main `package.json`, which is currently incorrectly populated by `ng-packagr` because the current build system builds all of these packages individually. I'm working on a fix to correctly configure `ng-packagr` and address the problem!

**Pull request merged**
