### PR TITLE
feat: added shade-slider component

### LINKED ISSUE #230: Simple Shade Slider
Hi, I would like to suggest a new feature for the color slider, this is a simple shade slider. this is just like a hue slider but the start color is the selected color from hue slider  going to a darker color
Capture

### PR DESCRIPTION
**Pull request by SeijiV13**
Fixes #230 added shade-slider feature for color picker

### CODE REVIEW

**Comment by SeijiV13** [comment]
## This PR contains the following updates
##### New Component - Color Slider Component
###### Usage
----
``` import { ColorSliderModule } from "ngx-color/slider";
  imports: [
    ColorSliderModule
  ],
     <color-shade-slider
            color="#fff" (onChangeComplete)="changeComplete($event)(onChange)="changeComplete($event)">
</color-shade-slider>```

**Comment by SeijiV13** [comment]
@scttcper let me know if you have any  issues  on this request :) cheers 💯

**Comment by scttcper** [comment]
thanks @SeijiV13 ! good component

**Pull request merged**
